Repository Tabeyouka/tabeyouka-frontend, pull requests merged in 2023-06, with the labels that each got.

#11 ✨feat : Add store information
  main/index.html
  main/main.css
  main/main.js
  signin/css/login.css
  signin/javascript/login.js
  signin/login.html
  signin/logo.png
Labels: 🎨 Html&css, ✨ Feature

#13 ✨feat : Add Rating Calculation Logic
  main/index.html
  main/main.css
  main/main.html
  main/main.js
Labels: ✨ Feature

#14 ✨feat : Add Rating Calculation Logic
  main/index.html
  main/main.css
  main/main.html
  main/main.js
Labels: ✨ Feature

#15 ✨ docs : Add main image and write style and logic
  main/main.css
  main/main.html
  main/main.js
  main/tabeyoukaLogo.png
Labels: ✨ Feature

#18 ✨ Implementing an SPA using vanilla JavaScript
  signin/javascript/login.js
  signin/login.html
Labels: ✨ Feature

#19 ✨feat : Implementing an SPA using vanilla JavaScript, Add main image and write style and logic
  main/main.css
  main/main.html
  main/main.js
  main/tabeyoukaLogo.png
  signin/javascript/login.js
  signin/login.html
Labels: ✨ Feature

#21 ✨ feat : Add link logic to other pages
  image/logo_mini.png
  image/tabeyouka:white.png
  image/tabeyoukaLogo.png
  main/main.css
  main/main.html
  main/main.js
  search/search.css
  search/search.html
  search/search.js
  signin/login.html
Labels: 📃 Docs, ✨ Feature, 🐞 BugFix

#22 ✨ feat : Add link logic to other pages
  image/logo_mini.png
  image/tabeyouka:white.png
  image/tabeyoukaLogo.png
  main/main.css
  main/main.html
  main/main.js
  search/search.css
  search/search.html
  search/search.js
  signin/login.html
Labels: 📃 Docs, ✨ Feature, 🐞 BugFix

#23 ✨ feat: Implementing a community Develop + etc
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  image/tabeyouka_white.png
  signin/css/login.css
  signin/javascript/login.js
  signin/login.html
Labels: 📃 Docs, ✨ Feature

#24 ✨ feat: Implementing a community Develop + etc
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  image/tabeyouka_white.png
  signin/css/login.css
  signin/javascript/login.js
  signin/login.html
Labels: 📃 Docs, ✨ Feature, 🔨 Refactor

#25 💄 style: UI Improvement
  community/css/list.css
  community/list.html
  community/post.html
  signin/css/login.css
  signin/javascript/login.js
  signin/login.html
Labels: 🎨 Html&css

#26 💄 style: UI Improvement
  community/css/list.css
  community/list.html
  community/post.html
  signin/css/login.css
  signin/javascript/login.js
  signin/login.html
Labels: 🎨 Html&css

#27 ✨ feat : Create registerPage, reviewPage, introducePage
  Register/Register.html
  Register/Register.js
  Register/main.css
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  introducepage/tabeyoukaLogo.png
  registerpage/Register.html
  registerpage/Register.js
  registerpage/main.css
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  reviewpage/tabeyoukaLogo.png
Labels: 🎨 Html&css, ✨ Feature

#28 ✨ feat : Create registerPage, reviewPage, introducePage
  Register/Register.html
  Register/Register.js
  Register/main.css
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  introducepage/tabeyoukaLogo.png
  registerpage/Register.html
  registerpage/Register.js
  registerpage/main.css
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  reviewpage/tabeyoukaLogo.png
Labels: 🎨 Html&css, ✨ Feature

#31 🐛 fix : Resolving parsing errors
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  main/main.html
  main/main.js
  search/search.html
  search/search.js
  signin/javascript/login.js
  signin/login.html
Labels: 🐞 BugFix

#34 🐛 fix : Old codes to lasted codes
  Register/Register.js
Labels: 🐞 BugFix

#35 🐛 fix : Old codes to lasted codes
  Register/Register.js
Labels: 🐞 BugFix

#37 ✨feat : Create Community detail page, Post modify page
  community/css/detail.css
  community/detail.html
  community/js/detail.js
  community/js/postModify.js
  community/postModify.html
Labels: 🎨 Html&css, 📃 Docs, ✨ Feature

#39 🔨 chore : Edit page linking
  Register/Register.html
  Register/Register.js
  community/list.html
  community/post.html
  introducepage/introduce.html
  introducepage/tabeyoukaLogo.png
  main/main.js
  reviewpage/review.html
  reviewpage/tabeyoukaLogo.png
  signin/javascript/login.js
  signin/login.html
Labels: 🔨 Refactor

#42 ✨ feat : Implement and update CRUD functionality for teammate introduction
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: ✨ Feature, 🐞 BugFix

#41 ✨ feat : Add page link
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.html
  main/main.js
  search/search.html
  search/search.js
  teammate/teammate.html
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature, 🐞 BugFix

#43 ✨ feat : Add page link
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.html
  main/main.js
  search/search.html
  search/search.js
  teammate/teammate.html
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature, 🐞 BugFix

#44 ✨ feat : Update Register
  Register/Register.js
  registerpage/Register.html
  registerpage/Register.js
  registerpage/main.css
Labels: ✨ Feature

#45 ✨ feat : Update Register
  Register/Register.js
  registerpage/Register.html
  registerpage/Register.js
  registerpage/main.css
Labels: ✨ Feature

#48 ✨feat : add comment modify/delete logic & post modify logic
  community/js/detail.js
  community/js/postModify.js
Labels: ✨ Feature

#47 ✨ feat : Update Register
  Register/Register.js
Labels: ✨ Feature

#49 ✨ feat : Update Register
  Register/Register.js
Labels: ✨ Feature

#50 🎨 refactor : Store information import and star rating management refactoring
  main/main.html
  main/main.js
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  search/search.css
  signin/javascript/login.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#51 🎨 refactor : Store information import and star rating management refactoring
  main/main.html
  main/main.js
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  search/search.css
  signin/javascript/login.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#53 ✨ feat: add status logic
  signin/javascript/login.js
Labels: ✨ Feature

#55 🐛 fix : Teammate CRUD error
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🐞 BugFix

#56 🐛 fix : Fix logic to determine logged in or not
  signin/javascript/login.js
  signin/login.html
Labels: 🐞 BugFix

#57 🐛 fix : Fix logic to determine logged in or not
  signin/javascript/login.js
  signin/login.html
Labels: 🐞 BugFix

#58 🐛 fix : Fix error in teammate modification feature
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🐞 BugFix

#59 🐛 fix : Fix error in teammate modification feature
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🐞 BugFix

#60 updates to the community logic, add fetch main page
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  signin/javascript/login.js
Labels: ✨ Feature, 🔨 Refactor

#61 updates to the community logic, add fetch main page
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  signin/javascript/login.js
Labels: ✨ Feature, 🔨 Refactor

#63 feat: add fetch detail.html etc 3
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/list.html
  community/post.html
  signin/javascript/login.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor, 🐞 BugFix

#64 feat: add fetch detail.html etc 3
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/list.html
  community/post.html
  signin/javascript/login.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor, 🐞 BugFix

#65 🔨 chore : Fixed image slider title text not going out of the element
  main/main.css
  main/main.html
Labels: 🐞 BugFix

#66 🔨 chore : Fixed image slider title text not going out of the element
  main/main.css
  main/main.html
Labels: 🐞 BugFix

#68 🐛 fix : Fix issue with SPA
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🐞 BugFix

#69 Add logic for community communication (creation button) etc 2
  community/css/list.css
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  main/main.js
Labels: ✨ Feature, 🔨 Refactor

#70 Add logic for community communication (creation button) etc 2
  community/css/list.css
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  main/main.js
Labels: ✨ Feature, 🔨 Refactor

#71 🔨 chore: Modify list.html fetch Logic
  main/main.js
Labels: 🔨 Refactor

#72 🔨 chore: Modify list.html fetch Logic
  main/main.js
Labels: 🔨 Refactor

#75 ✨ feat : Refresh when adding, deleting, or editing
  main/main.css
  main/main.html
  main/main.js
  search/search.css
  teammate/teammate.js
Labels: ✨ Feature

#77 Developfeat: Add logic for local storage(post_id) etc1
  community/detail.html
  community/js/list.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#78 feat: Add logic for local storage(post_id) etc1
  community/detail.html
  community/js/list.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#79 ✨ feat : Add logout and modify header style
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/js/post.js
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.css
  main/main.js
  reviewpage/reviewc.css
  search/search.css
  search/search.js
  signin/javascript/login.js
  teammate/teammate.css
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature

#80 ✨ feat : Add logout and modify header style
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/js/list.js
  community/js/post.js
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.css
  main/main.js
  reviewpage/reviewc.css
  search/search.css
  search/search.js
  signin/javascript/login.js
  teammate/teammate.css
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature

#82 ✨feat: add community post writer etc1
  community/js/list.js
  community/js/post.js
  community/list.html
  signin/javascript/login.js
Labels: ✨ Feature, 🔨 Refactor

#83 💄 style: Add responsive interface css style
  community/css/list.css
Labels: 🎨 Html&css

#84 💄 style: Add responsive interface css style
  community/css/list.css
Labels: 🎨 Html&css

#85 ✨ feat : Added move from search page to review page
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/detail.html
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  community/postModify.html
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.css
  main/main.html
  main/main.js
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  search/search.css
  search/search.html
  search/search.js
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature

#87 ✨ feat : Added move from search page to review page
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/detail.html
  community/js/list.js
  community/js/post.js
  community/list.html
  community/post.html
  community/postModify.html
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
  main/main.css
  main/main.html
  main/main.js
  reviewpage/review.html
  reviewpage/reviewc.css
  reviewpage/reviewj.js
  search/search.css
  search/search.html
  search/search.js
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: 🎨 Html&css, ✨ Feature

#88 🎨 refactor : Improve code readability and maintainability
  teammate/teammate.js
Labels: 🔨 Refactor

#90 🔨 chore: Delete unnecessary code
  community/js/list.js
Labels: 🔨 Refactor

#91 🔨 chore: Delete unnecessary code
  community/js/list.js
Labels: 🔨 Refactor

#92 ✨feat : add postId to fetch logic & add modal to input new comments
  community/css/detail.css
  community/detail.html
  community/js/detail.js
  community/js/postModify.js
  community/postModify.html
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#93 ✨feat : add postId to fetch logic & add modal to input new comments
  community/css/detail.css
  community/detail.html
  community/js/detail.js
  community/js/postModify.js
  community/postModify.html
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#94 🔨 chore : tidy up comments
  main/main.css
  main/main.js
  search/search.html
  search/search.js
Labels: 🔨 Refactor

#95 🔨 chore : tidy up comments
  main/main.css
  main/main.js
  search/search.html
  search/search.js
Labels: 🔨 Refactor

#96 ✨ feat : Implement admin-only screen
  teammate/teammate.css
  teammate/teammate.js
Labels: ✨ Feature

#97 ✨ feat : Implement admin-only screen
  teammate/teammate.css
  teammate/teammate.js
Labels: ✨ Feature

#100 feat: modify the logic for search results etc2
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/postModify.html
Labels: ✨ Feature, 🔨 Refactor

#101 feat: modify the logic for search results etc2
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/postModify.html
Labels: ✨ Feature, 🔨 Refactor

#103 Develop
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/js/postModify.js
  community/list.html
  community/post.html
  community/postModify.html
  signin/login.html
Labels: ✨ Feature, 🔨 Refactor

#104 🔨 chore: code modification
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/js/postModify.js
  community/list.html
  community/post.html
  community/postModify.html
  signin/login.html
Labels: ✨ Feature, 🔨 Refactor

#105 ✨ feat: Add comment Fetch loginDevelop
  community/detail.html
  community/js/detail.js
Labels: ✨ Feature

#106 ✨ feat: Add comment Fetch loginDevelop
  community/detail.html
  community/js/detail.js
Labels: ✨ Feature

#107 🎨 refactor: Improve code readability and maintainability
  teammate/teammate.css
  teammate/teammate.js
Labels: 🔨 Refactor

#108 🎨 refactor: Improve code readability and maintainability
  teammate/teammate.css
  teammate/teammate.js
Labels: 🔨 Refactor

#109 feat : Link posts, post edit pages to other pages and check if you are logged in
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/js/post.js
  community/js/postModify.js
  community/postModify.html
  introducepage/introduceC.css
  main/main.js
  reviewpage/reviewc.css
  search/search.css
  teammate/teammate.css
Labels: 🎨 Html&css, ✨ Feature

#110 ✨ feat : Link posts, post edit pages to other pages and check if you are logged in
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  community/detail.html
  community/js/detail.js
  community/js/list.js
  community/js/post.js
  community/js/postModify.js
  community/postModify.html
  introducepage/introduceC.css
  main/main.js
  reviewpage/reviewc.css
  search/search.css
  teammate/teammate.css
Labels: 🎨 Html&css, ✨ Feature

#111 ✨ feat : add new logic to make comment form when register comment
  community/css/detail.css
  community/detail.html
  community/js/detail.js
  community/js/postModify.js
  community/postModify.html
Labels: 🎨 Html&css, ✨ Feature

#112 ✨ feat : add new logic to make comment form when register comment
  community/css/detail.css
  community/detail.html
  community/js/detail.js
  community/js/postModify.js
  community/postModify.html
Labels: 🎨 Html&css, ✨ Feature

#113 JavaScript code refactoring etc 2
  community/js/list.js
  community/js/post.js
  community/list.html
  signin/javascript/login.js
  signin/login.html
Labels: 🔨 Refactor, 🐞 BugFix

#114 JavaScript code refactoring etc 2
  community/js/list.js
  community/js/post.js
  community/list.html
  signin/javascript/login.js
  signin/login.html
Labels: 🔨 Refactor, 🐞 BugFix

#115 ✨ feat : add Footer
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: ✨ Feature

#116 ✨ feat : add Footer
  teammate/teammate.css
  teammate/teammate.html
  teammate/teammate.js
Labels: ✨ Feature

#117 💄 style : Modify header responsiveness
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  introducepage/introduceC.css
  main/main.css
  main/main.html
  reviewpage/reviewc.css
  search/search.css
  teammate/teammate.css
Labels: 🎨 Html&css

#118 💄 style : Modify header responsiveness
  community/css/detail.css
  community/css/list.css
  community/css/post.css
  introducepage/introduceC.css
  main/main.css
  main/main.html
  reviewpage/reviewc.css
  search/search.css
  teammate/teammate.css
Labels: 🎨 Html&css

#119 ✨ feat : add comment form when register comment & allow comment modifying/deleting registered by own
  community/css/detail.css
  community/detail.html
  community/js/detail.js
Labels: 🎨 Html&css, ✨ Feature

#120 ✨ feat : add comment form when register comment & allow comment modifying/deleting registered by own
  community/css/detail.css
  community/detail.html
  community/js/detail.js
Labels: 🎨 Html&css, ✨ Feature

#123 🔨 chore: Remove console.log
  community/js/list.js
  community/js/post.js
  signin/javascript/login.js
Labels: 🔨 Refactor

#124 🔨 chore: Remove console.log
  community/js/list.js
  community/js/post.js
  signin/javascript/login.js
Labels: 🔨 Refactor

#125 ✨ feat : Add review information to image slider and search completion page
  community/js/detail.js
  community/js/list.js
  community/js/post.js
  community/js/postModify.js
  introducepage/introduceJ.js
  main/main.js
  reviewpage/reviewj.js
  search/search.js
  teammate/teammate.js
Labels: ✨ Feature

#126 ✨ feat : Add review information to image slider and search completion page
  community/js/detail.js
  community/js/list.js
  community/js/post.js
  community/js/postModify.js
  introducepage/introduceJ.js
  main/main.js
  reviewpage/reviewj.js
  search/search.js
  teammate/teammate.js
Labels: ✨ Feature

#127 fix: community image bug fix
  community/detail.html
  community/js/detail.js
Labels: 🐞 BugFix

#128 fix: community image bug fix
  community/detail.html
  community/js/detail.js
Labels: 🐞 BugFix

#129 ✨ feat : Add localsemester modal
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
Labels: ✨ Feature

#130 ✨ feat : Add localsemester modal
  introducepage/introduce.html
  introducepage/introduceC.css
  introducepage/introduceJ.js
Labels: ✨ Feature

#131 chore: modify html img tag
  community/detail.html
Labels: 🔨 Refactor

#132 chore: modify html img tag
  community/detail.html
Labels: 🔨 Refactor

#133 ✨ feat : show user nickname who wrote comments / 🔨 chore : fix comment modify/delete logic
  community/js/detail.js
  community/js/postModify.js
Labels: 🎨 Html&css, ✨ Feature

#134 ✨ feat : show user nickname who wrote comments / 🔨 chore : fix comment modify/delete logic
  community/js/detail.js
  community/js/postModify.js
Labels: 🎨 Html&css, ✨ Feature

#135 🎨 refactor : Release comment for testing
  main/main.js
Labels: 🔨 Refactor

#136 🎨 refactor : Release comment for testing
  main/main.js
Labels: 🔨 Refactor

#137 💄 style : Footer html, style unification
  community/css/detail.css
  community/detail.html
  community/list.html
  community/post.html
  community/postModify.html
  introducepage/introduce.html
  reviewpage/review.html
  reviewpage/reviewc.css
  search/search.html
  teammate/teammate.html
Labels: 🎨 Html&css

#139 💄 style : Footer html, style unification
  community/css/detail.css
  community/detail.html
  community/list.html
  community/post.html
  community/postModify.html
  introducepage/introduce.html
  reviewpage/review.html
  reviewpage/reviewc.css
  search/search.html
  teammate/teammate.html
Labels: 🎨 Html&css

#138 🎨 refactor : Add comments and clean up code
  teammate/teammate.js
Labels: 🔨 Refactor

#140 🎨 refactor : Add comments and clean up code
  teammate/teammate.js
Labels: 🔨 Refactor

#141 🐛 fix: community image bug fix
  community/js/detail.js
  community/js/postModify.js
Labels: 🐞 BugFix

#143 🔨 chore: Fixing incorrect code
  Register/Register.css
  Register/Register.html
  signin/javascript/login.js
Labels: 🎨 Html&css, 🔨 Refactor

#145 🔨 chore : Removed consolelog
  Register/Register.js
  introducepage/introduceJ.js
  reviewpage/reviewj.js
Labels: 🔨 Refactor

#146 🔨 chore : Removed consolelog
  Register/Register.js
  introducepage/introduceJ.js
  reviewpage/reviewj.js
Labels: 🔨 Refactor

#147 🔨 chore : Change color
  Register/Register.css
Labels: 🔨 Refactor

#148 🔨 chore : Change color
  Register/Register.css
Labels: 🔨 Refactor

#149 🔨 chore : Change color
  Register/Register.css
Labels: 🔨 Refactor

#150 🔨 chore : Change color
  Register/Register.css
Labels: 🔨 Refactor

#151 🔨 chore : Change font size
  Register/Register.css
Labels: 🔨 Refactor

#152 🔨 chore : Change font size
  Register/Register.css
Labels: 🔨 Refactor
